"""Cron registration for the unattended Self-Harness autopilot."""

from __future__ import annotations

from typing import Any

CRON_JOB_NAME = "governance_self_harness_autopilot"
DEFAULT_CRON_SCHEDULE = "0 4 * * *"  # daily 04:00 server time
_AUTOPILOT_SCRIPT_NAME = "governance_self_harness_autopilot.py"
AUTOPILOT_SCRIPT_TIMEOUT_SECONDS = 900


def register_self_harness_cron(
    *,
    schedule: str = DEFAULT_CRON_SCHEDULE,
    script_path: str = "",
    script_timeout_seconds: int = AUTOPILOT_SCRIPT_TIMEOUT_SECONDS,
) -> dict[str, Any] | None:
    """Register the unattended Self-Harness autopilot cron job idempotently."""

    from cron.jobs import create_job, list_jobs, update_job

    script_arg = script_path or _install_autopilot_script()

    for job in list_jobs(include_disabled=True):
        if str(job.get("name") or "") == CRON_JOB_NAME:
            updates: dict[str, Any] = {}
            if job.get("script") != script_arg:
                updates["script"] = script_arg
            if job.get("no_agent") is not True:
                updates["no_agent"] = True
            if job.get("script_timeout_seconds") != script_timeout_seconds:
                updates["script_timeout_seconds"] = script_timeout_seconds
            return update_job(str(job["id"]), updates) if updates else None

    return create_job(
        prompt=None,
        schedule=schedule,
        name=CRON_JOB_NAME,
        script=script_arg,
        no_agent=True,
        deliver="local",
        script_timeout_seconds=script_timeout_seconds,
    )


def _install_autopilot_script() -> str:
    """Write the autopilot runner into ~/.miho/scripts and return its basename."""

    from pathlib import Path

    from miho_constants import get_miho_home

    repo_root = Path(__file__).resolve().parents[2]
    scripts_dir = get_miho_home() / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    destination = scripts_dir / _AUTOPILOT_SCRIPT_NAME
    shim = (
        "#!/usr/bin/env python3\n"
        "# Auto-generated by governance_os.self_harness_cron. Do not edit by hand.\n"
        "import json\n"
        "import sys\n"
        f"sys.path.insert(0, {str(repo_root)!r})\n"
        "from plugins.governance_os.self_harness_loop import run_self_harness_autopilot\n"
        "summary = run_self_harness_autopilot()\n"
        "print(json.dumps(summary, ensure_ascii=False, indent=2))\n"
        "sys.exit(1 if summary.get('errors') else 0)\n"
    )
    destination.write_text(shim, encoding="utf-8")
    return _AUTOPILOT_SCRIPT_NAME
