"""LLM-polished Korean copy for academy guidance messages."""

from __future__ import annotations

import asyncio
import os
import re

from .commentary_config import (
    COMMENTARY_EXTRA_BODY,
    COMMENTARY_MODEL,
    COMMENTARY_PROVIDER,
)


GUIDANCE_COPY_TIMEOUT_SECONDS = 4
GUIDANCE_COPY_MAX_CHARS = 700
GUIDANCE_COPY_TASK = "academy_guidance_copy"
_URL_RE = re.compile(r"https?://\S+")
_COMMAND_RE = re.compile(r"/academy\s+login")
_FORBIDDEN_TERMS = (
    "400",
    "401",
    "403",
    "500",
    "cors",
    "traceback",
    "stack trace",
    "academy_id",
    "token",
    "토큰",
    "버그",
    "오류",
)


async def naturalize_guidance_response(*, user_text: str, intent: str, fallback: str) -> str:
    """Return warmer guidance without changing the facts generated by code.

    The LLM rewrites only the user-facing Korean copy. Login URLs, slash
    commands, connected account details, and admin-contact guidance must pass
    validation or the deterministic fallback is returned.
    """
    fallback = str(fallback or "").strip()
    if not fallback or not _enabled():
        return fallback
    try:
        candidate = await asyncio.wait_for(
            _call_llm(_messages(user_text=user_text, intent=intent, fallback=fallback)),
            timeout=GUIDANCE_COPY_TIMEOUT_SECONDS + 1,
        )
    except Exception:
        return fallback
    return _validated_copy(str(candidate or ""), fallback=fallback)


def _enabled() -> bool:
    value = os.getenv(
        "MIHO_ACADEMY_NATURAL_GUIDANCE_COPY",
        os.getenv("MIHO_ACADEMY_NATURAL_AUTH_COPY", "1"),
    )
    return value.strip().lower() not in {"0", "false", "no", "off"}


def _messages(*, user_text: str, intent: str, fallback: str) -> list[dict[str, str]]:
    return [
        {
            "role": "system",
            "content": (
                "너는 미호AI의 학원 업무 안내 문구만 작성한다. "
                "실제 로그인, 토큰, 권한 판단, 데이터 조회 결과는 이미 시스템 코드가 처리한다. "
                "제공된 고정 정보를 바꾸거나 빼지 말고 자연스러운 한국어 반말로만 다듬어라. "
                "HTTP 상태코드, CORS, 스택트레이스, 토큰, academy_id, 버그/오류 같은 "
                "개발자 표현은 절대 쓰지 마라. 응답은 1~4문장, 텍스트만 출력한다."
            ),
        },
        {
            "role": "user",
            "content": (
                f"사용자 요청: {user_text}\n"
                f"상황: {intent}\n"
                "반드시 보존할 고정 정보:\n"
                f"{fallback}\n\n"
                "위 고정 정보의 링크, 명령어, 이름, 학원명, 관리자 문의 안내, "
                "데이터 없음 판단을 유지하면서 사용자가 이해하기 쉽게 다시 말해줘."
            ),
        },
    ]


async def _call_llm(messages: list[dict[str, str]]) -> str:
    from agent.auxiliary_client import async_call_llm

    response = await async_call_llm(
        task=GUIDANCE_COPY_TASK,
        provider=COMMENTARY_PROVIDER,
        model=COMMENTARY_MODEL,
        messages=messages,
        temperature=0.4,
        max_tokens=220,
        timeout=GUIDANCE_COPY_TIMEOUT_SECONDS,
        extra_body=COMMENTARY_EXTRA_BODY,
    )
    return _response_text(response)


def _response_text(response: object) -> str:
    choices = getattr(response, "choices", None)
    if choices:
        message = getattr(choices[0], "message", None)
        content = getattr(message, "content", None)
        if content is not None:
            return str(content)
    return str(response or "")


def _validated_copy(candidate: str, *, fallback: str) -> str:
    text = _strip_code_fence(candidate).strip()
    if not (5 <= len(text) <= GUIDANCE_COPY_MAX_CHARS):
        return fallback
    lowered = text.lower()
    if any(term in lowered for term in _FORBIDDEN_TERMS):
        return fallback
    if not _preserves_required_fragments(text, fallback):
        return fallback
    return text


def _strip_code_fence(text: str) -> str:
    stripped = str(text or "").strip()
    if stripped.startswith("```") and stripped.endswith("```"):
        lines = stripped.splitlines()
        return "\n".join(lines[1:-1]).strip()
    return stripped


def _preserves_required_fragments(text: str, fallback: str) -> bool:
    if any(url not in text for url in _URL_RE.findall(fallback)):
        return False
    if _COMMAND_RE.search(fallback) and not _COMMAND_RE.search(text):
        return False
    if "관리자" in fallback and "관리자" not in text:
        return False
    if fallback.startswith("연결됨:"):
        for piece in _status_pieces(fallback):
            if piece and piece not in text:
                return False
    return True


def _status_pieces(fallback: str) -> list[str]:
    _, _, rest = fallback.partition(":")
    return [piece.strip() for piece in rest.split("/") if piece.strip()]
